name: Weekly Download of Uptime Check Files

on:
  schedule:
    - cron: '0 0 * * SUN' # Every Sunday at midnight UTC
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  download_json_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with full history
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download JSON files to root directory
      run: |
        curl -o ./alcea-wisteria.de.json https://alcea-wisteria.de/PHP//0demo/2025-08-04-UptimeCheck/alcea-wisteria.de.json
        curl -o ./alceawis.com.json https://alcea-wisteria.de/PHP//0demo/2025-08-04-UptimeCheck/alceawis.com.json
        curl -o ./alceawis.de.json https://alcea-wisteria.de/PHP//0demo/2025-08-04-UptimeCheck/alceawis.de.json

    - name: Commit and push changes
      run: |
        set -e
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add ./*.json
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Weekly download of uptime check JSON files"
          if ! git pull --rebase origin main; then
            echo "❌ Rebase failed due to conflicts. Keeping remote changes and skipping push."
            git rebase --abort || true
            exit 0
          fi
          git push origin main
        fi
